### ISSUE TITLE
Redact & Rotate Secrets

### ISSUE THREAD

**Issue by milesflo** [laukm/o365getmail#2]
https://github.com/laukm/o365getmail/blob/14f8869bd0baff52b6cfac29c58376a64830644f/o365getmail/config.py#L12

You have some committed secrets in your repo. Please remove them and replace them with ENV variables.

**Comment by laukm** [comment]
> https://github.com/laukm/o365getmail/blob/14f8869bd0baff52b6cfac29c58376a64830644f/o365getmail/config.py#L12
> 
> You have some committed secrets in your repo. Please remove them and replace them with ENV variables.

Thx, for letting me know, was by mistake ;-)
